In [1]:
# Pdf Extraction using PyPDF

In [2]:
!pip install pymupdf

Collecting pymupdf
  Obtaining dependency information for pymupdf from https://files.pythonhosted.org/packages/f5/fb/a3f1f8813f6e93c65d1f7ebca6530a889f1ae109229b537f7a617b2aab57/pymupdf-1.27.2-cp310-abi3-win_amd64.whl.metadata
  Downloading pymupdf-1.27.2-cp310-abi3-win_amd64.whl.metadata (3.4 kB)
Downloading pymupdf-1.27.2-cp310-abi3-win_amd64.whl (19.2 MB)
   ---------------------------------------- 0.0/19.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/19.2 MB 1.3 MB/s eta 0:00:16
   ---------------------------------------- 0.1/19.2 MB 1.1 MB/s eta 0:00:19
   ---------------------------------------- 0.2/19.2 MB 1.7 MB/s eta 0:00:12
    --------------------------------------- 0.4/19.2 MB 2.4 MB/s eta 0:00:08
   - -------------------------------------- 0.7/19.2 MB 3.0 MB/s eta 0:00:07
   -- ------------------------------------- 1.1/19.2 MB 4.0 MB/s eta 0:00:05
   -- ------------------------------------- 1.3/19.2 MB 4.1 MB/s eta 0:00:05
   --- ------------------------------------ 1.5/19.2 MB 4.3 MB/s eta 0:00:05
   --- ------------------------------------ 1.7/19.2 MB 4.6 MB/s eta 0:00:04
   ---- ----------------------------------- 2.0/19.2 MB 4.7 MB/s eta 0:00:04
   ---- ----------------------------------- 2.1/19.2 MB 4.4 MB/s eta 0:00:04
   ---- ----------------------------------- 2.2/19.2 MB 4.2 MB/s eta 0:00:05
   ---- ----------------------------------- 2.2/19.2 MB 4.2 MB/s eta 0:00:05
   ---- ----------------------------------- 2.2/19.2 MB 4.2 MB/s eta 0:00:05
   ---- ----------------------------------- 2.2/19.2 MB 4.2 MB/s eta 0:00:05
   ----- ---------------------------------- 2.5/19.2 MB 3.5 MB/s eta 0:00:05
   ------ --------------------------------- 3.3/19.2 MB 4.2 MB/s eta 0:00:04
   ------ --------------------------------- 3.3/19.2 MB 4.2 MB/s eta 0:00:04
   ------ --------------------------------- 3.3/19.2 MB 4.2 MB/s eta 0:00:04
   ------- -------------------------------- 3.6/19.2 MB 4.0 MB/s eta 0:00:04
   ------- -------------------------------- 3.8/19.2 MB 4.0 MB/s eta 0:00:04
   -------- ------------------------------- 3.9/19.2 MB 3.8 MB/s eta 0:00:05
   -------- ------------------------------- 3.9/19.2 MB 3.7 MB/s eta 0:00:05
   -------- ------------------------------- 4.0/19.2 MB 3.7 MB/s eta 0:00:05
   -------- ------------------------------- 4.1/19.2 MB 3.6 MB/s eta 0:00:05
   -------- ------------------------------- 4.1/19.2 MB 3.6 MB/s eta 0:00:05
   -------- ------------------------------- 4.2/19.2 MB 3.4 MB/s eta 0:00:05
   -------- ------------------------------- 4.3/19.2 MB 3.3 MB/s eta 0:00:05
   --------- ------------------------------ 4.3/19.2 MB 3.3 MB/s eta 0:00:05
   --------- ------------------------------ 4.4/19.2 MB 3.2 MB/s eta 0:00:05
   --------- ------------------------------ 4.5/19.2 MB 3.1 MB/s eta 0:00:05
   --------- ------------------------------ 4.5/19.2 MB 3.0 MB/s eta 0:00:05
   --------- ------------------------------ 4.5/19.2 MB 3.0 MB/s eta 0:00:05
   --------- ------------------------------ 4.6/19.2 MB 2.9 MB/s eta 0:00:05
   --------- ------------------------------ 4.7/19.2 MB 2.9 MB/s eta 0:00:06
   --------- ------------------------------ 4.7/19.2 MB 2.9 MB/s eta 0:00:06
   --------- ------------------------------ 4.8/19.2 MB 2.8 MB/s eta 0:00:06
   ---------- ----------------------------- 4.9/19.2 MB 2.8 MB/s eta 0:00:06
   ---------- ----------------------------- 4.9/19.2 MB 2.7 MB/s eta 0:00:06
   ---------- ----------------------------- 5.0/19.2 MB 2.7 MB/s eta 0:00:06
   ---------- ----------------------------- 5.0/19.2 MB 2.7 MB/s eta 0:00:06
   ---------- ----------------------------- 5.1/19.2 MB 2.6 MB/s eta 0:00:06
   ---------- ----------------------------- 5.2/19.2 MB 2.6 MB/s eta 0:00:06
   ---------- ----------------------------- 5.3/19.2 MB 2.6 MB/s eta 0:00:06
   ----------- ---------------------------- 5.3/19.2 MB 2.6 MB/s eta 0:00:06
   ----------- ---------------------------- 5.4/19.2 MB 2.5 MB/s eta 0:00:06
   ----------- ---------------------------- 5.5/19.2 MB 2.5 MB/s eta 0:00:06
   ----------- ---------------------------- 5.6/19.2 MB 2.5 MB/s eta 0:00:06
   ----------- ---------------------------- 5.6/19.2 MB 2.5 MB/s eta 0:00:06
   ----------- ---------------------------- 5.7/19.2 MB 2.5 MB/s eta 0:00:06
   ------------ --------------------------- 5.8/19.2 MB 2.5 MB/s eta 0:00:06
   ------------ --------------------------- 5.8/19.2 MB 2.4 MB/s eta 0:00:06
   ------------ --------------------------- 5.9/19.2 MB 2.4 MB/s eta 0:00:06
   ------------ --------------------------- 6.0/19.2 MB 2.4 MB/s eta 0:00:06
   ------------ --------------------------- 6.1/19.2 MB 2.4 MB/s eta 0:00:06
   ------------ --------------------------- 6.2/19.2 MB 2.4 MB/s eta 0:00:06
   ------------ --------------------------- 6.2/19.2 MB 2.4 MB/s eta 0:00:06
   ------------- -------------------------- 6.3/19.2 MB 2.4 MB/s eta 0:00:06
   ------------- -------------------------- 6.4/19.2 MB 2.3 MB/s eta 0:00:06
   ------------- -------------------------- 6.5/19.2 MB 2.3 MB/s eta 0:00:06
   ------------- -------------------------- 6.6/19.2 MB 2.3 MB/s eta 0:00:06
   ------------- -------------------------- 6.6/19.2 MB 2.3 MB/s eta 0:00:06
   ------------- -------------------------- 6.7/19.2 MB 2.3 MB/s eta 0:00:06
   -------------- ------------------------- 6.8/19.2 MB 2.3 MB/s eta 0:00:06
   -------------- ------------------------- 6.9/19.2 MB 2.3 MB/s eta 0:00:06
   -------------- ------------------------- 7.0/19.2 MB 2.3 MB/s eta 0:00:06
   -------------- ------------------------- 7.0/19.2 MB 2.3 MB/s eta 0:00:06
   -------------- ------------------------- 7.1/19.2 MB 2.3 MB/s eta 0:00:06
   -------------- ------------------------- 7.2/19.2 MB 2.3 MB/s eta 0:00:06
   --------------- ------------------------ 7.3/19.2 MB 2.3 MB/s eta 0:00:06
   --------------- ------------------------ 7.4/19.2 MB 2.3 MB/s eta 0:00:06
   --------------- ------------------------ 7.4/19.2 MB 2.3 MB/s eta 0:00:06
   --------------- ------------------------ 7.5/19.2 MB 2.2 MB/s eta 0:00:06
   --------------- ------------------------ 7.6/19.2 MB 2.2 MB/s eta 0:00:06
   ---------------- ----------------------- 7.7/19.2 MB 2.2 MB/s eta 0:00:06
   ---------------- ----------------------- 7.8/19.2 MB 2.2 MB/s eta 0:00:06
   ---------------- ----------------------- 7.9/19.2 MB 2.2 MB/s eta 0:00:06
   ---------------- ----------------------- 8.0/19.2 MB 2.2 MB/s eta 0:00:06
   ---------------- ----------------------- 8.1/19.2 MB 2.2 MB/s eta 0:00:06
   ---------------- ----------------------- 8.1/19.2 MB 2.2 MB/s eta 0:00:06
   ----------------- ---------------------- 8.2/19.2 MB 2.2 MB/s eta 0:00:05
   ----------------- ---------------------- 8.3/19.2 MB 2.2 MB/s eta 0:00:05
   ----------------- ---------------------- 8.4/19.2 MB 2.2 MB/s eta 0:00:05
   ----------------- ---------------------- 8.5/19.2 MB 2.2 MB/s eta 0:00:05
   ----------------- ---------------------- 8.6/19.2 MB 2.2 MB/s eta 0:00:05
   ------------------ --------------------- 8.7/19.2 MB 2.2 MB/s eta 0:00:05
   ------------------ --------------------- 8.8/19.2 MB 2.2 MB/s eta 0:00:05
   ------------------ --------------------- 8.9/19.2 MB 2.2 MB/s eta 0:00:05
   ------------------ --------------------- 9.0/19.2 MB 2.2 MB/s eta 0:00:05
   ------------------ --------------------- 9.1/19.2 MB 2.2 MB/s eta 0:00:05
   ------------------- -------------------- 9.2/19.2 MB 2.2 MB/s eta 0:00:05
   ------------------- -------------------- 9.2/19.2 MB 2.2 MB/s eta 0:00:05
   ------------------- -------------------- 9.3/19.2 MB 2.2 MB/s eta 0:00:05
   ------------------- -------------------- 9.4/19.2 MB 2.2 MB/s eta 0:00:05
   ------------------- -------------------- 9.5/19.2 MB 2.2 MB/s eta 0:00:05
   -------------------- ------------------- 9.6/19.2 MB 2.2 MB/s eta 0:00:05
   -------------------- ------------------- 9.7/19.2 MB 2.2 MB/s eta 0:00:05
   -------------------- ------------------- 9.8/19.2 MB 2.2 MB/s eta 0:00:05
   -------------------- ------------------- 9.9/19.2 MB 2.2 MB/s eta 0:00:05
   -------------------- ------------------- 10.0/19.2 MB 2.2 MB/s eta 0:00:05
   --------------------- ------------------ 10.1/19.2 MB 2.2 MB/s eta 0:00:05
   --------------------- ------------------ 10.2/19.2 MB 2.2 MB/s eta 0:00:05
   --------------------- ------------------ 10.3/19.2 MB 2.2 MB/s eta 0:00:05
   --------------------- ------------------ 10.4/19.2 MB 2.2 MB/s eta 0:00:05
   --------------------- ------------------ 10.5/19.2 MB 2.2 MB/s eta 0:00:04
   ---------------------- ----------------- 10.6/19.2 MB 2.2 MB/s eta 0:00:04
   ---------------------- ----------------- 10.7/19.2 MB 2.2 MB/s eta 0:00:04
   ---------------------- ----------------- 10.8/19.2 MB 2.2 MB/s eta 0:00:04
   ---------------------- ----------------- 10.9/19.2 MB 2.1 MB/s eta 0:00:04
   ---------------------- ----------------- 11.0/19.2 MB 2.1 MB/s eta 0:00:04
   ----------------------- ---------------- 11.1/19.2 MB 2.1 MB/s eta 0:00:04
   ----------------------- ---------------- 11.2/19.2 MB 2.1 MB/s eta 0:00:04
   ----------------------- ---------------- 11.3/19.2 MB 2.1 MB/s eta 0:00:04
   ----------------------- ---------------- 11.4/19.2 MB 2.1 MB/s eta 0:00:04
   ------------------------ --------------- 11.6/19.2 MB 2.1 MB/s eta 0:00:04
   ------------------------ --------------- 11.7/19.2 MB 2.0 MB/s eta 0:00:04
   ------------------------ --------------- 11.8/19.2 MB 2.0 MB/s eta 0:00:04
   ------------------------ --------------- 11.9/19.2 MB 2.0 MB/s eta 0:00:04
   ------------------------ --------------- 12.0/19.2 MB 2.0 MB/s eta 0:00:04
   ------------------------- -------------- 12.1/19.2 MB 2.0 MB/s eta 0:00:04
   ------------------------- -------------- 12.2/19.2 MB 2.0 MB/s eta 0:00:04
   ------------------------- -------------- 12.3/19.2 MB 2.0 MB/s eta 0:00:04
   ------------------------- -------------- 12.5/19.2 MB 2.1 MB/s eta 0:00:04
   -------------------------- ------------- 12.6/19.2 MB 2.0 MB/s eta 0:00:04
   -------------------------- ------------- 12.7/19.2 MB 2.0 MB/s eta 0:00:04
   -------------------------- ------------- 12.8/19.2 MB 2.0 MB/s eta 0:00:04
   -------------------------- ------------- 12.9/19.2 MB 2.0 MB/s eta 0:00:04
   --------------------------- ------------ 13.0/19.2 MB 2.0 MB/s eta 0:00:04
   --------------------------- ------------ 13.2/19.2 MB 2.0 MB/s eta 0:00:04
   --------------------------- ------------ 13.3/19.2 MB 2.0 MB/s eta 0:00:04
   --------------------------- ------------ 13.4/19.2 MB 1.9 MB/s eta 0:00:04
   ---------------------------- ----------- 13.5/19.2 MB 1.9 MB/s eta 0:00:03
   ---------------------------- ----------- 13.7/19.2 MB 2.0 MB/s eta 0:00:03
   ---------------------------- ----------- 13.8/19.2 MB 1.9 MB/s eta 0:00:03
   ---------------------------- ----------- 13.9/19.2 MB 1.9 MB/s eta 0:00:03
   ----------------------------- ---------- 14.0/19.2 MB 1.9 MB/s eta 0:00:03
   ----------------------------- ---------- 14.1/19.2 MB 1.9 MB/s eta 0:00:03
   ----------------------------- ---------- 14.2/19.2 MB 1.9 MB/s eta 0:00:03
   ----------------------------- ---------- 14.3/19.2 MB 2.0 MB/s eta 0:00:03
   ----------------------------- ---------- 14.4/19.2 MB 2.0 MB/s eta 0:00:03
   ------------------------------ --------- 14.5/19.2 MB 2.0 MB/s eta 0:00:03
   ------------------------------ --------- 14.6/19.2 MB 2.0 MB/s eta 0:00:03
   ------------------------------ --------- 14.7/19.2 MB 2.0 MB/s eta 0:00:03
   ------------------------------ --------- 14.9/19.2 MB 2.0 MB/s eta 0:00:03
   ------------------------------- -------- 15.0/19.2 MB 2.0 MB/s eta 0:00:03
   ------------------------------- -------- 15.1/19.2 MB 2.1 MB/s eta 0:00:03
   ------------------------------- -------- 15.2/19.2 MB 2.1 MB/s eta 0:00:02
   ------------------------------- -------- 15.3/19.2 MB 2.1 MB/s eta 0:00:02
   -------------------------------- ------- 15.4/19.2 MB 2.1 MB/s eta 0:00:02
   -------------------------------- ------- 15.5/19.2 MB 2.1 MB/s eta 0:00:02
   -------------------------------- ------- 15.6/19.2 MB 2.1 MB/s eta 0:00:02
   -------------------------------- ------- 15.7/19.2 MB 2.1 MB/s eta 0:00:02
   --------------------------------- ------ 15.9/19.2 MB 2.1 MB/s eta 0:00:02
   --------------------------------- ------ 16.0/19.2 MB 2.2 MB/s eta 0:00:02
   --------------------------------- ------ 16.1/19.2 MB 2.2 MB/s eta 0:00:02
   --------------------------------- ------ 16.2/19.2 MB 2.2 MB/s eta 0:00:02
   --------------------------------- ------ 16.3/19.2 MB 2.2 MB/s eta 0:00:02
   ---------------------------------- ----- 16.4/19.2 MB 2.2 MB/s eta 0:00:02
   ---------------------------------- ----- 16.5/19.2 MB 2.2 MB/s eta 0:00:02
   ---------------------------------- ----- 16.6/19.2 MB 2.2 MB/s eta 0:00:02
   ---------------------------------- ----- 16.8/19.2 MB 2.2 MB/s eta 0:00:02
   ----------------------------------- ---- 16.9/19.2 MB 2.2 MB/s eta 0:00:02
   ----------------------------------- ---- 17.0/19.2 MB 2.2 MB/s eta 0:00:01
   ----------------------------------- ---- 17.1/19.2 MB 2.3 MB/s eta 0:00:01
   ----------------------------------- ---- 17.2/19.2 MB 2.3 MB/s eta 0:00:01
   ------------------------------------ --- 17.4/19.2 MB 2.3 MB/s eta 0:00:01
   ------------------------------------ --- 17.5/19.2 MB 2.3 MB/s eta 0:00:01
   ------------------------------------ --- 17.6/19.2 MB 2.3 MB/s eta 0:00:01
   ------------------------------------ --- 17.7/19.2 MB 2.3 MB/s eta 0:00:01
   ------------------------------------- -- 17.9/19.2 MB 2.3 MB/s eta 0:00:01
   ------------------------------------- -- 18.0/19.2 MB 2.3 MB/s eta 0:00:01
   ------------------------------------- -- 18.0/19.2 MB 2.3 MB/s eta 0:00:01
   ------------------------------------- -- 18.2/19.2 MB 2.3 MB/s eta 0:00:01
   ------------------------------------- -- 18.3/19.2 MB 2.3 MB/s eta 0:00:01
   -------------------------------------- - 18.4/19.2 MB 2.3 MB/s eta 0:00:01
   -------------------------------------- - 18.5/19.2 MB 2.4 MB/s eta 0:00:01
   -------------------------------------- - 18.6/19.2 MB 2.3 MB/s eta 0:00:01
   -------------------------------------- - 18.7/19.2 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  18.9/19.2 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  19.0/19.2 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  19.1/19.2 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  19.2/19.2 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  19.2/19.2 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  19.2/19.2 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 19.2/19.2 MB 2.3 MB/s eta 0:00:00
Installing collected packages: pymupdf
Successfully installed pymupdf-1.27.2

Importing Libraries

In [1]:
import fitz
import pandas as pd
import re

Extracting data from the pdf

In [2]:
pdf_path = 'datasets\\a1988-59.pdf'

doc = fitz.open(pdf_path)

text = ""
for page in doc:
    text += page.get_text()

print("Text Length: ", len(text))

Text Length:  377391

Cleaning the text by adding spaces and sub

In [3]:
text = text.replace("\n", " ")
text = re.sub(r'\s+', ' ', text)

Detecting the chapters and sections, subsections as our dataset consists of the part such as 
(no): what the section is<br>
<t>(no): subsections explaining about the terms that also false under the section

In [4]:
rows = []

current_chapter = None
current_section = None

tokens = re.split(r'(?=\bCHAPTER\b|\d+\.)', text)

for token in tokens:
    
    # Detect chapter
    chap = re.search(r'CHAPTER\s+([IVXLC]+)', token)
    if chap:
        current_chapter = chap.group(1)
    
    # Detect section
    sec = re.match(r'(\d+)\.\s*(.*)', token)
    if sec:
        current_section = sec.group(1)
        rows.append({
            "chapter": current_chapter,
            "section": current_section,
            "subsection": "main",
            "text": sec.group(2).strip()
        })
    
    # Detect subsections (i), (ii), (iii)
    subs = re.findall(r'\((i+|v|x+)\)\s*(.*?)(?=\(\w+\)|Explanation|$)', token)
    for s in subs:
        rows.append({
            "chapter": current_chapter,
            "section": current_section,
            "subsection": s[0],
            "text": s[1].strip()
        })
    
    # Detect explanation
    exp = re.search(r'Explanation\.\—(.*)', token)
    if exp:
        rows.append({
            "chapter": current_chapter,
            "section": current_section,
            "subsection": "explanation",
            "text": exp.group(1).strip()
        })

In [5]:
df = pd.DataFrame(rows)
df.head(20)

,chapter,section,subsection,text
0,I,1,main,"Short title, extent and commencement."
1,I,2,main,Definitions. 2A. e-cart and e-rickshaw.
2,II,3,main,Necessity for driving licence.
3,II,4,main,Age limit in connection with driving of motor ...
4,II,5,main,Responsibility of owners of motor vehicles for...
5,II,4,main,
6,II,6,main,Restrictions on the holding of driving licences.
7,II,7,main,Restrictions on the granting of learner’s lice...
8,II,8,main,Grant of learner’s licence.
9,II,9,main,Grant of driving licence.
10,II,0,main,Form and contents of licences to drive.
11,II,1,main,Additions to driving licence.
12,II,2,main,Licensing and regulation of schools or establi...
13,II,3,main,"Extent of effectiveness of licences, to drive ..."
14,II,4,main,Currency of licences to drive motor vehicles.
15,II,5,main,Renewal of driving licences.
16,II,6,main,Revocation of driving licence on grounds of di...
17,II,7,main,Orders refusing or revoking driving licences a...
18,II,8,main,"Driving Licences to drive motor vehicles, belo..."
19,II,9,main,Power of licensing authority to disqualify fro...

In [6]:
df.to_csv("Motor_Vehicle_Act_Dataset.csv", index= False)
print("Dataset saved successfully")

Dataset saved successfully

In [7]:
def chunk_text(text, size= 200):
    words = text.split()
    for i in range(0, len(words), size):
        yield " ".join(words[i:i+size])

In [19]:
df1 = pd.read_csv('datasets\\Motor_Vehicle_Act_Dataset.csv')
df1.head()

,chapter,section,subsection,text
0,I,1,main,"Short title, extent and commencement."
1,I,2,main,Definitions. 2A. e-cart and e-rickshaw.
2,II,3,main,Necessity for driving licence.
3,II,4,main,Age limit in connection with driving of motor ...
4,II,5,main,Responsibility of owners of motor vehicles for...